/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Abuse
 */
export interface Abuse {
    /**
     * 
     * @type {string}
     * @memberof Abuse
     */
    'route'?: string;
    /**
     * 
     * @type {string}
     * @memberof Abuse
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof Abuse
     */
    'handle'?: string;
    /**
     * 
     * @type {string}
     * @memberof Abuse
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Abuse
     */
    'organization'?: string;
    /**
     * 
     * @type {string}
     * @memberof Abuse
     */
    'role'?: string;
    /**
     * 
     * @type {string}
     * @memberof Abuse
     */
    'kind'?: string;
    /**
     * 
     * @type {string}
     * @memberof Abuse
     */
    'address'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Abuse
     */
    'emails'?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Abuse
     */
    'phone_numbers'?: Array<string>;
}

