/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ASNResponseAsn } from './asnresponse-asn';

/**
 * 
 * @export
 * @interface ASNResponse
 */
export interface ASNResponse {
    /**
     * IP address for which ASN information is returned. Present if the \'ip\' query parameter is used or no IP is specified (defaults to requester\'s IP).
     * @type {string}
     * @memberof ASNResponse
     */
    'ip'?: string;
    /**
     * 
     * @type {ASNResponseAsn}
     * @memberof ASNResponse
     */
    'asn'?: ASNResponseAsn;
}

