/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ASNResponseXMLAsn } from './asnresponse-xmlasn';

/**
 * 
 * @export
 * @interface ASNResponseXML
 */
export interface ASNResponseXML {
    /**
     * 
     * @type {string}
     * @memberof ASNResponseXML
     */
    'ip'?: string;
    /**
     * 
     * @type {ASNResponseXMLAsn}
     * @memberof ASNResponseXML
     */
    'asn'?: ASNResponseXMLAsn;
}

