/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ASNConnection } from './asnconnection';

/**
 * 
 * @export
 * @interface ASNResponseXMLAsn
 */
export interface ASNResponseXMLAsn {
    /**
     * 
     * @type {string}
     * @memberof ASNResponseXMLAsn
     */
    'as_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof ASNResponseXMLAsn
     */
    'organization'?: string;
    /**
     * 
     * @type {string}
     * @memberof ASNResponseXMLAsn
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof ASNResponseXMLAsn
     */
    'asn_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof ASNResponseXMLAsn
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof ASNResponseXMLAsn
     */
    'domain'?: string;
    /**
     * 
     * @type {string}
     * @memberof ASNResponseXMLAsn
     */
    'date_allocated'?: string;
    /**
     * 
     * @type {string}
     * @memberof ASNResponseXMLAsn
     */
    'allocation_status'?: string;
    /**
     * 
     * @type {number}
     * @memberof ASNResponseXMLAsn
     */
    'num_of_ipv4_routes'?: number;
    /**
     * 
     * @type {number}
     * @memberof ASNResponseXMLAsn
     */
    'num_of_ipv6_routes'?: number;
    /**
     * 
     * @type {string}
     * @memberof ASNResponseXMLAsn
     */
    'rir'?: string;
    /**
     * It will only be included in the response, if you set include=routes in the request
     * @type {Array<string>}
     * @memberof ASNResponseXMLAsn
     */
    'routes'?: Array<string>;
    /**
     * 
     * @type {Array<ASNConnection>}
     * @memberof ASNResponseXMLAsn
     */
    'upstreams'?: Array<ASNConnection>;
    /**
     * 
     * @type {Array<ASNConnection>}
     * @memberof ASNResponseXMLAsn
     */
    'downstreams'?: Array<ASNConnection>;
    /**
     * 
     * @type {Array<ASNConnection>}
     * @memberof ASNResponseXMLAsn
     */
    'peers'?: Array<ASNConnection>;
    /**
     * 
     * @type {string}
     * @memberof ASNResponseXMLAsn
     */
    'whois_response'?: string;
}

