/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AstronomyEvening } from './astronomy-evening';
// May contain unused imports in some cases
// @ts-ignore
import type { AstronomyMorning } from './astronomy-morning';

/**
 * 
 * @export
 * @interface Astronomy
 */
export interface Astronomy {
    /**
     * 
     * @type {string}
     * @memberof Astronomy
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof Astronomy
     */
    'current_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof Astronomy
     */
    'mid_night'?: string;
    /**
     * 
     * @type {string}
     * @memberof Astronomy
     */
    'night_end'?: string;
    /**
     * 
     * @type {AstronomyMorning}
     * @memberof Astronomy
     */
    'morning'?: AstronomyMorning;
    /**
     * 
     * @type {string}
     * @memberof Astronomy
     */
    'sunrise'?: string;
    /**
     * 
     * @type {string}
     * @memberof Astronomy
     */
    'sunset'?: string;
    /**
     * 
     * @type {AstronomyEvening}
     * @memberof Astronomy
     */
    'evening'?: AstronomyEvening;
    /**
     * 
     * @type {string}
     * @memberof Astronomy
     */
    'night_begin'?: string;
    /**
     * 
     * @type {string}
     * @memberof Astronomy
     */
    'sun_status'?: string;
    /**
     * 
     * @type {string}
     * @memberof Astronomy
     */
    'solar_noon'?: string;
    /**
     * 
     * @type {string}
     * @memberof Astronomy
     */
    'day_length'?: string;
    /**
     * 
     * @type {number}
     * @memberof Astronomy
     */
    'sun_altitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof Astronomy
     */
    'sun_distance'?: number;
    /**
     * 
     * @type {number}
     * @memberof Astronomy
     */
    'sun_azimuth'?: number;
    /**
     * 
     * @type {string}
     * @memberof Astronomy
     */
    'moon_phase'?: string;
    /**
     * 
     * @type {string}
     * @memberof Astronomy
     */
    'moonrise'?: string;
    /**
     * 
     * @type {string}
     * @memberof Astronomy
     */
    'moonset'?: string;
    /**
     * 
     * @type {string}
     * @memberof Astronomy
     */
    'moon_status'?: string;
    /**
     * 
     * @type {number}
     * @memberof Astronomy
     */
    'moon_altitude'?: number;
    /**
     * 
     * @type {number}
     * @memberof Astronomy
     */
    'moon_distance'?: number;
    /**
     * 
     * @type {number}
     * @memberof Astronomy
     */
    'moon_azimuth'?: number;
    /**
     * 
     * @type {number}
     * @memberof Astronomy
     */
    'moon_parallactic_angle'?: number;
    /**
     * 
     * @type {string}
     * @memberof Astronomy
     */
    'moon_illumination_percentage'?: string;
    /**
     * 
     * @type {number}
     * @memberof Astronomy
     */
    'moon_angle'?: number;
}

