/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AstronomyMorning
 */
export interface AstronomyMorning {
    /**
     * 
     * @type {string}
     * @memberof AstronomyMorning
     */
    'astronomical_twilight_begin'?: string;
    /**
     * 
     * @type {string}
     * @memberof AstronomyMorning
     */
    'astronomical_twilight_end'?: string;
    /**
     * 
     * @type {string}
     * @memberof AstronomyMorning
     */
    'nautical_twilight_begin'?: string;
    /**
     * 
     * @type {string}
     * @memberof AstronomyMorning
     */
    'nautical_twilight_end'?: string;
    /**
     * 
     * @type {string}
     * @memberof AstronomyMorning
     */
    'civil_twilight_begin'?: string;
    /**
     * 
     * @type {string}
     * @memberof AstronomyMorning
     */
    'civil_twilight_end'?: string;
    /**
     * 
     * @type {string}
     * @memberof AstronomyMorning
     */
    'blue_hour_begin'?: string;
    /**
     * 
     * @type {string}
     * @memberof AstronomyMorning
     */
    'blue_hour_end'?: string;
    /**
     * 
     * @type {string}
     * @memberof AstronomyMorning
     */
    'golden_hour_begin'?: string;
    /**
     * 
     * @type {string}
     * @memberof AstronomyMorning
     */
    'golden_hour_end'?: string;
}

