/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CountryMetadata
 */
export interface CountryMetadata {
    /**
     * 
     * @type {string}
     * @memberof CountryMetadata
     */
    'calling_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof CountryMetadata
     */
    'tld'?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof CountryMetadata
     */
    'languages'?: Array<string>;
}

