/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Abuse } from './abuse';
// May contain unused imports in some cases
// @ts-ignore
import type { CountryMetadata } from './country-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { Location } from './location';
// May contain unused imports in some cases
// @ts-ignore
import type { Network } from './network';
// May contain unused imports in some cases
// @ts-ignore
import type { Security } from './security';
// May contain unused imports in some cases
// @ts-ignore
import type { TimeZone } from './time-zone';
// May contain unused imports in some cases
// @ts-ignore
import type { UserAgentData } from './user-agent-data';

/**
 * 
 * @export
 * @interface GeolocationXMLResponse
 */
export interface GeolocationXMLResponse {
    /**
     * 
     * @type {string}
     * @memberof GeolocationXMLResponse
     */
    'ip'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeolocationXMLResponse
     */
    'hostname'?: string;
    /**
     * 
     * @type {string}
     * @memberof GeolocationXMLResponse
     */
    'domain'?: string;
    /**
     * 
     * @type {Location}
     * @memberof GeolocationXMLResponse
     */
    'location'?: Location;
    /**
     * 
     * @type {CountryMetadata}
     * @memberof GeolocationXMLResponse
     */
    'country_metadata'?: CountryMetadata;
    /**
     * 
     * @type {Network}
     * @memberof GeolocationXMLResponse
     */
    'network'?: Network;
    /**
     * 
     * @type {Currency}
     * @memberof GeolocationXMLResponse
     */
    'currency'?: Currency;
    /**
     * 
     * @type {Security}
     * @memberof GeolocationXMLResponse
     */
    'security'?: Security;
    /**
     * 
     * @type {Abuse}
     * @memberof GeolocationXMLResponse
     */
    'abuse'?: Abuse;
    /**
     * 
     * @type {TimeZone}
     * @memberof GeolocationXMLResponse
     */
    'time_zone'?: TimeZone;
    /**
     * 
     * @type {UserAgentData}
     * @memberof GeolocationXMLResponse
     */
    'user_agent'?: UserAgentData;
}

