/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Abuse } from './abuse';
// May contain unused imports in some cases
// @ts-ignore
import type { CountryMetadata } from './country-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { ErrorXMLResponseArray } from './error-xmlresponse-array';
// May contain unused imports in some cases
// @ts-ignore
import type { GeolocationXMLResponseArray } from './geolocation-xmlresponse-array';
// May contain unused imports in some cases
// @ts-ignore
import type { Location } from './location';
// May contain unused imports in some cases
// @ts-ignore
import type { Network } from './network';
// May contain unused imports in some cases
// @ts-ignore
import type { Security } from './security';
// May contain unused imports in some cases
// @ts-ignore
import type { TimeZone } from './time-zone';
// May contain unused imports in some cases
// @ts-ignore
import type { UserAgentData } from './user-agent-data';

/**
 * @type GetBulkIpGeolocation200ResponseInner1
 * @export
 */
export type GetBulkIpGeolocation200ResponseInner1 = ErrorXMLResponseArray | GeolocationXMLResponseArray;


