/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CountryMetadata } from './country-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { ErrorResponse } from './error-response';
// May contain unused imports in some cases
// @ts-ignore
import type { LocationMinimal } from './location-minimal';
// May contain unused imports in some cases
// @ts-ignore
import type { NetworkMinimal } from './network-minimal';
// May contain unused imports in some cases
// @ts-ignore
import type { Security } from './security';
// May contain unused imports in some cases
// @ts-ignore
import type { SecurityAPIResponse } from './security-apiresponse';
// May contain unused imports in some cases
// @ts-ignore
import type { TimeZone } from './time-zone';
// May contain unused imports in some cases
// @ts-ignore
import type { UserAgentData } from './user-agent-data';

/**
 * @type GetBulkIpSecurityInfo200ResponseInner
 * @export
 */
export type GetBulkIpSecurityInfo200ResponseInner = ErrorResponse | SecurityAPIResponse;


