/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetBulkIpGeolocationRequest
 */
export interface GetBulkIpGeolocationRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof GetBulkIpGeolocationRequest
     */
    'ips'?: Array<string>;
}

