/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Location
 */
export interface Location {
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'continent_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'continent_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'country_code2'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'country_code3'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'country_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'country_name_official'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'country_capital'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'state_prov'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'state_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'district'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'zipcode'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'latitude'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'longitude'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Location
     */
    'is_eu'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'country_flag'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'geoname_id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'country_emoji'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'accuracy_radius'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'locality'?: string;
    /**
     * 
     * @type {string}
     * @memberof Location
     */
    'dma_code'?: string;
}

