/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NetworkAsn
 */
export interface NetworkAsn {
    /**
     * 
     * @type {string}
     * @memberof NetworkAsn
     */
    'as_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkAsn
     */
    'organization'?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkAsn
     */
    'country'?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkAsn
     */
    'asn_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkAsn
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkAsn
     */
    'domain'?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkAsn
     */
    'date_allocated'?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkAsn
     */
    'allocation_status'?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkAsn
     */
    'num_of_ipv4_routes'?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkAsn
     */
    'num_of_ipv6_routes'?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkAsn
     */
    'rir'?: string;
}

