/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface NetworkMinimalAsn
 */
export interface NetworkMinimalAsn {
    /**
     * 
     * @type {string}
     * @memberof NetworkMinimalAsn
     */
    'as_number'?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkMinimalAsn
     */
    'organization'?: string;
    /**
     * 
     * @type {string}
     * @memberof NetworkMinimalAsn
     */
    'country'?: string;
}

