/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Security
 */
export interface Security {
    /**
     * 
     * @type {number}
     * @memberof Security
     */
    'threat_score'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof Security
     */
    'is_tor'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Security
     */
    'is_proxy'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Security
     */
    'proxy_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof Security
     */
    'proxy_provider'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Security
     */
    'is_anonymous'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Security
     */
    'is_known_attacker'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Security
     */
    'is_spam'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Security
     */
    'is_bot'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Security
     */
    'is_cloud_provider'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Security
     */
    'cloud_provider'?: string;
}

