/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CountryMetadata } from './country-metadata';
// May contain unused imports in some cases
// @ts-ignore
import type { Currency } from './currency';
// May contain unused imports in some cases
// @ts-ignore
import type { LocationMinimal } from './location-minimal';
// May contain unused imports in some cases
// @ts-ignore
import type { NetworkMinimal } from './network-minimal';
// May contain unused imports in some cases
// @ts-ignore
import type { Security } from './security';
// May contain unused imports in some cases
// @ts-ignore
import type { TimeZone } from './time-zone';
// May contain unused imports in some cases
// @ts-ignore
import type { UserAgentData } from './user-agent-data';

/**
 * 
 * @export
 * @interface SecurityAPIXMLResponseArray
 */
export interface SecurityAPIXMLResponseArray {
    /**
     * 
     * @type {string}
     * @memberof SecurityAPIXMLResponseArray
     */
    'ip'?: string;
    /**
     * 
     * @type {string}
     * @memberof SecurityAPIXMLResponseArray
     */
    'hostname'?: string;
    /**
     * 
     * @type {Security}
     * @memberof SecurityAPIXMLResponseArray
     */
    'security'?: Security;
    /**
     * 
     * @type {LocationMinimal}
     * @memberof SecurityAPIXMLResponseArray
     */
    'location'?: LocationMinimal;
    /**
     * 
     * @type {NetworkMinimal}
     * @memberof SecurityAPIXMLResponseArray
     */
    'network'?: NetworkMinimal;
    /**
     * 
     * @type {TimeZone}
     * @memberof SecurityAPIXMLResponseArray
     */
    'time_zone'?: TimeZone;
    /**
     * 
     * @type {UserAgentData}
     * @memberof SecurityAPIXMLResponseArray
     */
    'user_agent'?: UserAgentData;
    /**
     * 
     * @type {CountryMetadata}
     * @memberof SecurityAPIXMLResponseArray
     */
    'country_metadata'?: CountryMetadata;
    /**
     * 
     * @type {Currency}
     * @memberof SecurityAPIXMLResponseArray
     */
    'currency'?: Currency;
}

