/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TimeConversionXMLResponse
 */
export interface TimeConversionXMLResponse {
    /**
     * 
     * @type {string}
     * @memberof TimeConversionXMLResponse
     */
    'original_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimeConversionXMLResponse
     */
    'converted_time'?: string;
    /**
     * 
     * @type {number}
     * @memberof TimeConversionXMLResponse
     */
    'diff_hour'?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeConversionXMLResponse
     */
    'diff_min'?: number;
}

