/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TimezoneDetailDstEnd } from './timezone-detail-dst-end';
// May contain unused imports in some cases
// @ts-ignore
import type { TimezoneDetailDstStart } from './timezone-detail-dst-start';

/**
 * 
 * @export
 * @interface TimezoneDetail
 */
export interface TimezoneDetail {
    /**
     * 
     * @type {string}
     * @memberof TimezoneDetail
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof TimezoneDetail
     */
    'offset'?: number;
    /**
     * 
     * @type {number}
     * @memberof TimezoneDetail
     */
    'offset_with_dst'?: number;
    /**
     * 
     * @type {string}
     * @memberof TimezoneDetail
     */
    'date'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneDetail
     */
    'date_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneDetail
     */
    'date_time_txt'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneDetail
     */
    'date_time_wti'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneDetail
     */
    'date_time_ymd'?: string;
    /**
     * 
     * @type {number}
     * @memberof TimezoneDetail
     */
    'date_time_unix'?: number;
    /**
     * 
     * @type {string}
     * @memberof TimezoneDetail
     */
    'time_24'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneDetail
     */
    'time_12'?: string;
    /**
     * 
     * @type {number}
     * @memberof TimezoneDetail
     */
    'week'?: number;
    /**
     * 
     * @type {number}
     * @memberof TimezoneDetail
     */
    'month'?: number;
    /**
     * 
     * @type {number}
     * @memberof TimezoneDetail
     */
    'year'?: number;
    /**
     * 
     * @type {string}
     * @memberof TimezoneDetail
     */
    'year_abbr'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TimezoneDetail
     */
    'is_dst'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TimezoneDetail
     */
    'dst_savings'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TimezoneDetail
     */
    'dst_exists'?: boolean;
    /**
     * 
     * @type {TimezoneDetailDstStart}
     * @memberof TimezoneDetail
     */
    'dst_start'?: TimezoneDetailDstStart;
    /**
     * 
     * @type {TimezoneDetailDstEnd}
     * @memberof TimezoneDetail
     */
    'dst_end'?: TimezoneDetailDstEnd;
}

