/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TimezoneAirport
 */
export interface TimezoneAirport {
    /**
     * 
     * @type {string}
     * @memberof TimezoneAirport
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneAirport
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneAirport
     */
    'latitude'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneAirport
     */
    'longitude'?: string;
    /**
     * 
     * @type {number}
     * @memberof TimezoneAirport
     */
    'elevation_ft'?: number;
    /**
     * 
     * @type {string}
     * @memberof TimezoneAirport
     */
    'continent_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneAirport
     */
    'country_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneAirport
     */
    'state_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneAirport
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneAirport
     */
    'iata_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneAirport
     */
    'icao_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneAirport
     */
    'faa_code'?: string;
}

