/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TimezoneAirport } from './timezone-airport';
// May contain unused imports in some cases
// @ts-ignore
import type { TimezoneDetail } from './timezone-detail';
// May contain unused imports in some cases
// @ts-ignore
import type { TimezoneLocation } from './timezone-location';
// May contain unused imports in some cases
// @ts-ignore
import type { TimezoneLocode } from './timezone-locode';

/**
 * 
 * @export
 * @interface TimeZoneDetailedXMLResponse
 */
export interface TimeZoneDetailedXMLResponse {
    /**
     * 
     * @type {string}
     * @memberof TimeZoneDetailedXMLResponse
     */
    'ip'?: string;
    /**
     * 
     * @type {TimezoneAirport}
     * @memberof TimeZoneDetailedXMLResponse
     */
    'airport_details'?: TimezoneAirport;
    /**
     * 
     * @type {TimezoneLocode}
     * @memberof TimeZoneDetailedXMLResponse
     */
    'lo_code_details'?: TimezoneLocode;
    /**
     * 
     * @type {TimezoneLocation}
     * @memberof TimeZoneDetailedXMLResponse
     */
    'location'?: TimezoneLocation;
    /**
     * 
     * @type {TimezoneDetail}
     * @memberof TimeZoneDetailedXMLResponse
     */
    'time_zone'?: TimezoneDetail;
}

