/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TimeZoneDstEnd
 */
export interface TimeZoneDstEnd {
    /**
     * 
     * @type {string}
     * @memberof TimeZoneDstEnd
     */
    'utc_time'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimeZoneDstEnd
     */
    'duration'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TimeZoneDstEnd
     */
    'gap'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TimeZoneDstEnd
     */
    'date_time_after'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimeZoneDstEnd
     */
    'date_time_before'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TimeZoneDstEnd
     */
    'overlap'?: boolean;
}

