/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { TimeZoneDstEnd } from './time-zone-dst-end';
// May contain unused imports in some cases
// @ts-ignore
import type { TimeZoneDstStart } from './time-zone-dst-start';

/**
 * 
 * @export
 * @interface TimeZone
 */
export interface TimeZone {
    /**
     * 
     * @type {string}
     * @memberof TimeZone
     */
    'name'?: string;
    /**
     * 
     * @type {number}
     * @memberof TimeZone
     */
    'offset'?: number;
    /**
     * 
     * @type {number}
     * @memberof TimeZone
     */
    'offset_with_dst'?: number;
    /**
     * 
     * @type {string}
     * @memberof TimeZone
     */
    'current_time'?: string;
    /**
     * 
     * @type {number}
     * @memberof TimeZone
     */
    'current_time_unix'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TimeZone
     */
    'is_dst'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof TimeZone
     */
    'dst_savings'?: number;
    /**
     * 
     * @type {boolean}
     * @memberof TimeZone
     */
    'dst_exists'?: boolean;
    /**
     * 
     * @type {TimeZoneDstStart}
     * @memberof TimeZone
     */
    'dst_start'?: TimeZoneDstStart;
    /**
     * 
     * @type {TimeZoneDstEnd}
     * @memberof TimeZone
     */
    'dst_end'?: TimeZoneDstEnd;
}

