/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TimezoneLocation
 */
export interface TimezoneLocation {
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocation
     */
    'location_string'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocation
     */
    'continent_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocation
     */
    'continent_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocation
     */
    'country_code2'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocation
     */
    'country_code3'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocation
     */
    'country_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocation
     */
    'country_name_official'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof TimezoneLocation
     */
    'is_eu'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocation
     */
    'state_prov'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocation
     */
    'state_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocation
     */
    'district'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocation
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocation
     */
    'locality'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocation
     */
    'zipcode'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocation
     */
    'latitude'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocation
     */
    'longitude'?: string;
}

