/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface TimezoneLocode
 */
export interface TimezoneLocode {
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocode
     */
    'lo_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocode
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocode
     */
    'state_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocode
     */
    'country_code'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocode
     */
    'country_name'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocode
     */
    'location_type'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocode
     */
    'latitude'?: string;
    /**
     * 
     * @type {string}
     * @memberof TimezoneLocode
     */
    'longitude'?: string;
}

