/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserAgentDataEngine
 */
export interface UserAgentDataEngine {
    /**
     * 
     * @type {string}
     * @memberof UserAgentDataEngine
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAgentDataEngine
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAgentDataEngine
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAgentDataEngine
     */
    'version_major'?: string;
}

