/* tslint:disable */
/* eslint-disable */
/**
 * IPGeolocation.io - IP intelligence products
 * Ipgeolocation provides a set of APIs to make ip based decisions.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { UserAgentDataDevice } from './user-agent-data-device';
// May contain unused imports in some cases
// @ts-ignore
import type { UserAgentDataEngine } from './user-agent-data-engine';
// May contain unused imports in some cases
// @ts-ignore
import type { UserAgentDataOperatingSystem } from './user-agent-data-operating-system';

/**
 * 
 * @export
 * @interface UserAgentXMLDataArray
 */
export interface UserAgentXMLDataArray {
    /**
     * 
     * @type {string}
     * @memberof UserAgentXMLDataArray
     */
    'user_agent_string'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAgentXMLDataArray
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAgentXMLDataArray
     */
    'type'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAgentXMLDataArray
     */
    'version'?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAgentXMLDataArray
     */
    'version_major'?: string;
    /**
     * 
     * @type {UserAgentDataDevice}
     * @memberof UserAgentXMLDataArray
     */
    'device'?: UserAgentDataDevice;
    /**
     * 
     * @type {UserAgentDataEngine}
     * @memberof UserAgentXMLDataArray
     */
    'engine'?: UserAgentDataEngine;
    /**
     * 
     * @type {UserAgentDataOperatingSystem}
     * @memberof UserAgentXMLDataArray
     */
    'operating_system'?: UserAgentDataOperatingSystem;
}

